image_input_topic: "/raspicam_node/image"
#image_input_topic: "/camera/color/image_raw"
face_detected_image_topic: "/face_detector/raw_image"
haar_file_face: "/home/robot/newman_ws/src/face_tracker_newman/data/face.xml"
face_tracking: 1
display_original_image: 0
display_tracking_image: 1
